# docker-compose.yml
version: '1.0'

services:
  data-analysis:
    build:
      context: ./data-analysis
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./data-analysis:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8010"]

